### ISSUE TITLE
mvn test fails for jnario-maven-report-plugin [Branch: no_xtend_xtext2.9]

### ISSUE THREAD

**Issue by riederm** [borisbrodski/Jnario#9]
i'm currently putting some new effort into the jnario project.

before i want to integrate my stuff back to @borisbrodski xtext.2.9 branch, i wanted to make an automated build using travis to make sure that everything is still building also apart from my machine.

travis does a `mvn install` and a `mvn test` run. The `mvn test` fails with following error: 

> Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor failed: The source must not be a directory.

Unfortunately google doesnt help a lot, at least it didnt help me :(
see https://travis-ci.org/riederm/Jnario/builds/217608357

now following lines from the pom.xml are responsible: 
https://github.com/borisbrodski/Jnario/blob/no_xtend_xtext2.9/plugins/jnario-maven-report-plugin/pom.xml#L86
```xml
<plugin>

	<artifactId>maven-plugin-plugin</artifactId>
	<version>3.4</version>
        <executions>
             <execution>
                   <id>default-descriptor</id>
                   <phase>process-classes</phase>
             </execution>
        </executions>
	<configuration>
	</configuration>
</plugin>
```

I'm not so familiar with maven, so i have no idea what it does and why it is important.
@borisbrodski are these lines important for the report-maven plugin? previous branches have other (shorter) versions wihtout the execution.

If I can get the build running, I think I have some interesting stuff to push. I moved jnario to xtext 2.11 and i ported the original xtend-richstring code to its own grammar based on xbase and made Jnario use this. So real native xtend-like richstrings for jnario.

**Comment by borisbrodski** [comment]
Hi,

I'm exactly on this right now :)

In travis you can freely choose, which commands are used to build the project.
Nevertheless, `mvn test` should work.

Cheers,
Boris

**Comment by borisbrodski** [comment]
Travis build works now: https://travis-ci.org/borisbrodski/Jnario/

**Comment by riederm** [comment]
awesome! i re-merged your branch, travis now also builds my branch
